#!/bin/bash

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
    brew bundle check > /dev/null 2>&1 || {
        echo "==> ${GREEN}Installing ${RED}Brew${GREEN} dependencies${NC}"
        brew bundle
    }
fi

echo -e "==> ${GREEN}Installing Python dependencies${NC}"
poetry install --quiet --no-interaction --with dev
echo -e "==> ${GREEN}Remember to commit your ${RED}poetry.lock${GREEN} file${NC}"
